# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mcmc_cpp <- function(N_iter, n_ranks, N_parm, nline_data, data_NlineNdim, sigma_RanksParm, transit_BetaParm, logpost_all_ranks, i_accumul, i_accumul_accept, n_iter_a_stack_base, n_iter_a_batch_base, n_iter_a_batch_rand, Swapmode, i_save_begin, N_stoptune, ar_ok_upper, ar_ok_lower, sigma_parm_min, sigma_parm_max, sigma_jumpin_ratio, sigma_scale_half_ratio, n_iter_in_tune, ar_best, ar_accept_diff, init_gp_ratio, para_min, para_max, Beta_Values, results_dir) {
    .Call(`_cppfiles_run_mcmc_cpp`, N_iter, n_ranks, N_parm, nline_data, data_NlineNdim, sigma_RanksParm, transit_BetaParm, logpost_all_ranks, i_accumul, i_accumul_accept, n_iter_a_stack_base, n_iter_a_batch_base, n_iter_a_batch_rand, Swapmode, i_save_begin, N_stoptune, ar_ok_upper, ar_ok_lower, sigma_parm_min, sigma_parm_max, sigma_jumpin_ratio, sigma_scale_half_ratio, n_iter_in_tune, ar_best, ar_accept_diff, init_gp_ratio, para_min, para_max, Beta_Values, results_dir)
}

r8_normal_01 <- function() {
    .Call(`_cppfiles_r8_normal_01`)
}

r8_normal_ab <- function(a, b) {
    .Call(`_cppfiles_r8_normal_ab`, a, b)
}

r8_logunif_ab <- function(a, b) {
    .Call(`_cppfiles_r8_logunif_ab`, a, b)
}

r8_unif_ab <- function(a, b) {
    .Call(`_cppfiles_r8_unif_ab`, a, b)
}

i4_unif_ab <- function(a, b) {
    .Call(`_cppfiles_i4_unif_ab`, a, b)
}

i4_unif_0a <- function(a) {
    .Call(`_cppfiles_i4_unif_0a`, a)
}

normal_pdf <- function(x, mean, sd) {
    .Call(`_cppfiles_normal_pdf`, x, mean, sd)
}

save_first_chain_cpp <- function(chain_parm, path, i_rank, logpost_first, N_parm, FoutPre, FoutSuf) {
    .Call(`_cppfiles_save_first_chain_cpp`, chain_parm, path, i_rank, logpost_first, N_parm, FoutPre, FoutSuf)
}

save_init_parm_cpp <- function(transit_BetaParm, path, n_ranks, N_parm) {
    .Call(`_cppfiles_save_init_parm_cpp`, transit_BetaParm, path, n_ranks, N_parm)
}

save_the_seed_cpp <- function(seed, path, i_rank) {
    .Call(`_cppfiles_save_the_seed_cpp`, seed, path, i_rank)
}

save_sigma_gauss_prop_cpp <- function(ptr_sigma_prop, i_rank, results_dir, N_parm) {
    .Call(`_cppfiles_save_sigma_gauss_prop_cpp`, ptr_sigma_prop, i_rank, results_dir, N_parm)
}

save_ar_stack_cpp <- function(i_next_stack, n_iter_a_stack, accept_rate_a_stack, n_ranks, results_dir) {
    .Call(`_cppfiles_save_ar_stack_cpp`, i_next_stack, n_iter_a_stack, accept_rate_a_stack, n_ranks, results_dir)
}

save_the_batch_cpp <- function(chain_IterParm_cpp, n_iter_a_batch, path, i_rank, logpost, accumul, accumul_accept, N_parm, FoutPre, FoutSuf) {
    .Call(`_cppfiles_save_the_batch_cpp`, chain_IterParm_cpp, n_iter_a_batch, path, i_rank, logpost, accumul, accumul_accept, N_parm, FoutPre, FoutSuf)
}

save_log_posterior_cpp <- function(one_chain_new_cpp, logll_temper_new, logprior_new, path, i_rank, N_parm, FoutPre, FoutSuf) {
    .Call(`_cppfiles_save_log_posterior_cpp`, one_chain_new_cpp, logll_temper_new, logprior_new, path, i_rank, N_parm, FoutPre, FoutSuf)
}

save_debug_gaussian_proposal_cpp <- function(one_chain, sigma_prop, results_dir, N_parm) {
    .Call(`_cppfiles_save_debug_gaussian_proposal_cpp`, one_chain, sigma_prop, results_dir, N_parm)
}

save_debug_stack_doswap_cpp <- function(so_swap, results_dir) {
    .Call(`_cppfiles_save_debug_stack_doswap_cpp`, so_swap, results_dir)
}

save_debug_stack_sequence_cpp <- function(i_accumul, i_swap, results_dir) {
    .Call(`_cppfiles_save_debug_stack_sequence_cpp`, i_accumul, i_swap, results_dir)
}

save_tuning_sigma_ar_cpp <- function(ar_ParmNvaried, sigma_alltune_ParmNvaried, path, rank_in_tune, n_ranks, N_parm) {
    .Call(`_cppfiles_save_tuning_sigma_ar_cpp`, ar_ParmNvaried, sigma_alltune_ParmNvaried, path, rank_in_tune, n_ranks, N_parm)
}

save_the_batch_tune_cpp <- function(chain_IterParm_cpp, n_iter_a_batch, path, i_rank, rank_in_tune, logpost, N_parm, FoutPre, FoutSuf) {
    .Call(`_cppfiles_save_the_batch_tune_cpp`, chain_IterParm_cpp, n_iter_a_batch, path, i_rank, rank_in_tune, logpost, N_parm, FoutPre, FoutSuf)
}

period_to_au_cpp <- function(period_days, ms_Msun) {
    .Call(`_cppfiles_period_to_au_cpp`, period_days, ms_Msun)
}

calc_osi_cpp <- function(mp_Mearth, ms_Msun, a_AU, d_pc) {
    .Call(`_cppfiles_calc_osi_cpp`, mp_Mearth, ms_Msun, a_AU, d_pc)
}

newton_solver_cpp <- function(EE_init, e) {
    .Call(`_cppfiles_newton_solver_cpp`, EE_init, e)
}

func_as_cpp <- function(time_con, Nline_time, ecc, osi, cosi, OmegaO, M0, omega, per, Ntime_radec) {
    .Call(`_cppfiles_func_as_cpp`, time_con, Nline_time, ecc, osi, cosi, OmegaO, M0, omega, per, Ntime_radec)
}

log_likelihood_cpp <- function(Nline_time, Ntime_radec, data_radec, var_uk) {
    .Call(`_cppfiles_log_likelihood_cpp`, Nline_time, Ntime_radec, data_radec, var_uk)
}

logll_beta_cpp <- function(ptr_one_chain_cpp, nline_data, data_cpp, i_rank, beta_values_cpp) {
    .Call(`_cppfiles_logll_beta_cpp`, ptr_one_chain_cpp, nline_data, data_cpp, i_rank, beta_values_cpp)
}

init_gaussian_proposal_cpp <- function(para_min, para_max, init_gp_ratio) {
    .Call(`_cppfiles_init_gaussian_proposal_cpp`, para_min, para_max, init_gp_ratio)
}

bounce_inside_cpp <- function(para, para_min, para_max) {
    .Call(`_cppfiles_bounce_inside_cpp`, para, para_min, para_max)
}

para_boundary_cpp <- function(one_chain_new_cpp, para_min_cpp, para_max_cpp) {
    .Call(`_cppfiles_para_boundary_cpp`, one_chain_new_cpp, para_min_cpp, para_max_cpp)
}

prior_para0_cpp <- function(para0_min, para0_max) {
    .Call(`_cppfiles_prior_para0_cpp`, para0_min, para0_max)
}

prior_para1_cpp <- function(para1_min, para1_max) {
    .Call(`_cppfiles_prior_para1_cpp`, para1_min, para1_max)
}

prior_para2_cpp <- function(para2_min, para2_max) {
    .Call(`_cppfiles_prior_para2_cpp`, para2_min, para2_max)
}

prior_para3_cpp <- function(para3_min, para3_max) {
    .Call(`_cppfiles_prior_para3_cpp`, para3_min, para3_max)
}

prior_para4_cpp <- function(para4_min, para4_max) {
    .Call(`_cppfiles_prior_para4_cpp`, para4_min, para4_max)
}

prior_para5_cpp <- function(para5, para5_min, para5_max) {
    .Call(`_cppfiles_prior_para5_cpp`, para5, para5_min, para5_max)
}

prior_para6_cpp <- function(para6, para6_min, para6_max) {
    .Call(`_cppfiles_prior_para6_cpp`, para6, para6_min, para6_max)
}

prior_para7_cpp <- function(para7, para7_min, para7_max) {
    .Call(`_cppfiles_prior_para7_cpp`, para7, para7_min, para7_max)
}

prior_para8_cpp <- function(para8_min, para8_max) {
    .Call(`_cppfiles_prior_para8_cpp`, para8_min, para8_max)
}

prior_para9_cpp <- function(para9_min, para9_max) {
    .Call(`_cppfiles_prior_para9_cpp`, para9_min, para9_max)
}

prior_para10_cpp <- function(para10_min, para10_max) {
    .Call(`_cppfiles_prior_para10_cpp`, para10_min, para10_max)
}

prior_para11_cpp <- function(para11_min, para11_max) {
    .Call(`_cppfiles_prior_para11_cpp`, para11_min, para11_max)
}

prior_para12_cpp <- function(para12_min, para12_max) {
    .Call(`_cppfiles_prior_para12_cpp`, para12_min, para12_max)
}

prior_para13_cpp <- function(para13, para13_min, para13_max) {
    .Call(`_cppfiles_prior_para13_cpp`, para13, para13_min, para13_max)
}

prior_para14_cpp <- function(para14, para14_min, para14_max) {
    .Call(`_cppfiles_prior_para14_cpp`, para14, para14_min, para14_max)
}

log_prior_cpp <- function(ptr_one_chain_cpp, para_min_cpp, para_max_cpp) {
    .Call(`_cppfiles_log_prior_cpp`, ptr_one_chain_cpp, para_min_cpp, para_max_cpp)
}

save_debug_para_boundary_cpp <- function(p_s, p, p_min, p_max, result_dir) {
    invisible(.Call(`_cppfiles_save_debug_para_boundary_cpp`, p_s, p, p_min, p_max, result_dir))
}

